---
config:
  flowchart:
    curve: linear
---
graph TD;
	PromptInput([PromptInput]):::first
	WithFallbacks(WithFallbacks)
	PydanticToolsParserOutput([PydanticToolsParserOutput]):::last
	PromptInput --> WithFallbacks;
	WithFallbacks --> PydanticToolsParserOutput;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
